name: AceTheGame CI
on: [push, workflow_dispatch, pull_request]

jobs:
  ACE:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: "apt update"
        run: sudo apt-get update
      - name: "install compiler and build tools"
        run: sudo apt-get install build-essential -y

      - name: create build directory
        working-directory: ./ACE
        run: mkdir build

      # Debug build
      - name: debug build
        working-directory: ./ACE/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug ../
          make -j$(nproc)

      - name: debug unit test
        working-directory: ./ACE/build
        run: ./test/test_ace -s

      - name: upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ace-debug
          path: ./ACE/build/*

      # Release build
      - name: release build
        working-directory: ./ACE/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release ../ 
          make -j$(nproc)

      - name: release unit test
        working-directory: ./ACE/build
        run: ./test/test_ace -s

      - name: upload release artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ace-release
          path: ./ACE/build/*

  Modder-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: "apt update"
        run: sudo apt-get update
      - name: "install build dependencies"
        run: sudo apt-get install openjdk-17-jdk-headless apktool gradle -y

      - name: generating code for injection
        working-directory: ./Modder/injector
        run: python3 ./gen_smali.py

      - name: build
        working-directory: ./Modder
        run: ./gradlew build -x test

      - name: test
        working-directory: ./Modder
        run: ./gradlew test

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: modder-linux
          path: ./Modder/build/libs/*

  Modder-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' 
          java-version: '17'

      - name: "install build tools"
        run: choco install apktool --version=2.5.0

      - name: "install pkgconfig"
        run: choco install pkgconfiglite

      - name: generating code for injection
        working-directory: ./Modder/injector
        run: python ./gen_smali.py

      - name: build
        working-directory: ./Modder
        run: ./gradlew build -x test

      - name: test
        working-directory: ./Modder
        run: ./gradlew test

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: modder-windows
          path: ./Modder/build/libs/*

  ATG:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: "apt update"
        run: sudo apt-get update
      - name: "install build dependencies"
        run: sudo apt-get install openjdk-17-jdk-headless fd-find -y

      - name: "setup JAVA_HOME to java 17"
        run: |
          JAVA_HOME=$(fdfind java-17 /usr/lib/jvm | xargs readlink -f)
          echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "JAVA_HOME set to ${JAVA_HOME}"

      - name: build
        working-directory: ./ATG
        run: ./gradlew assembleDebug

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: atg
          path: ./ATG/app/build/outputs/apk/debug/*

  billing-hack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: "apt update"
        run: sudo apt-get update
      - name: "install build dependencies"
        run: sudo apt-get install openjdk-17-jdk-headless fd-find -y

      - name: "setup JAVA_HOME to java 17"
        run: |
          JAVA_HOME=$(fdfind java-17 /usr/lib/jvm | xargs readlink -f)
          echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "JAVA_HOME set to ${JAVA_HOME}"

      - name: build
        working-directory: ./billing-hack
        run: ./gradlew assembleDebug

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: billing-hack
          path: ./billing-hack/build/outputs/apk/debug/*
